service: my-telegram-bot

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1
  environment:
    TELEGRAM_TOKEN: ${env:TELEGRAM_TOKEN}

functions:
  post:
    handler: handler.handler
    events:
      - http:
          path: telegram/alert
          method: post
          cors: true
      - http:
          path: telegram/musicConverter
          method: post
          cors: true
