#!/bin/bash

function stepinfo {
  echo -e "\033[1;32m===> $1\033[0m"
}

function succ {
  echo "  ✅ done"
}

function fail {
  echo -e "\033[1;31m  ⛔ $1\033[0m"
}

stepinfo "Checking node version"
correct_node_version=$(node -v 2>&1 | grep 'v14.15.4')
if [[ -z "$correct_node_version" ]]
then
    # Read more about this bug here: https://github.com/serverless/serverless/issues/8794
    fail "Node version must be v14.15.4 due to a zero-byte bug with serverless-python-requirements. Set with: 'sudo n 14.15.4'."
else
    succ
fi

stepinfo "Setting env variables"
. secrets/env
succ

stepinfo "Installing node packages"
npm ci
succ

stepinfo "Syncing Poetry packages"
poetry install --sync --no-root
succ

stepinfo "Initializing pre-commit hooks"
poetry run pre-commit install
succ
