version: 2.1

orbs:
  python: circleci/python@2.0.3
jobs:
  build_and_test:
    docker:
      - image: circleci/python:3.9
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
          args: --no-root  # important for docker - install dependencies only, not this project
      - run: echo $TELEGRAM_ALERT_GROUP
      - run: poetry run pytest -m 'not integ' -rf
      # will require a way to store gmusic .cred file and integration context
      # - run: poetry run pytest -m 'integ' -rf --log-level=WARNING
workflows:
  main:
    jobs:
      - build_and_test:
          context: Integration  # still required for unit tests
