version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run: Setup env
          command: |
            sudo pip install pipenv
            source setup
      - run: pipenv run pytest -m 'not integ' -rf
      - run: pipenv run pytest -m 'integ' -rf --log-level=WARNING


workflows:
  main:
    jobs:
      - build-and-test
