version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.6
    executor: python/default
    steps:
      - checkout
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run: |
          sudo pip install pipenv
          pipenv install
      - run: pipenv run pytest -m 'not integ' -rf
      - run: pipenv run pytest -m 'integ' -rf --log-level=WARNING
      - store_test_results:
          path: test-results


workflows:
  main:
    jobs:
      - build-and-test
          context: integration
